name: Ponto Cingo
on:
  schedule:
    # 10:55 UTC = 07:55 Brasil (Prepara para as 08h)
    - cron: '55 10 * * 1-5'
    # 19:55 UTC = 16:55 Brasil (Prepara para as 17h)
    - cron: '55 19 * * 1-5'
  workflow_dispatch: # Permite que você rode manualmente para testar

jobs:
  bater_ponto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executar Script
        env:
          CINGO_USER: ${{ secrets.CINGO_USER }}
          CINGO_PASS: ${{ secrets.CINGO_PASS }}
        run: |
          pip install requests
          python ponto.py
